--Xoa bang neu co
DROP TABLE HSBA CASCADE CONSTRAINTS;
DROP TABLE HSBA_DV CASCADE CONSTRAINTS;
DROP TABLE BENHNHAN CASCADE CONSTRAINTS;
DROP TABLE CSYT CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;

--Tao cac bang
CREATE TABLE HSBA (
    MAHSBA VARCHAR2(10),
    MABN VARCHAR2(10),
    NGAY DATE,
    CHANDOAN VARCHAR2(255),
    MABS VARCHAR2(10),
    MAKHOA VARCHAR2(10),
    MACSYT VARCHAR2(10),
    KETLUAN VARCHAR2(255),
    CONSTRAINT PK_HSBA PRIMARY KEY (MAHSBA)
);

CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(10),
    MADV VARCHAR2(10),
    NGAY DATE,
    MAKTV VARCHAR2(10),
    KETQUA VARCHAR2(255),
    CONSTRAINT PK_HSBA_DV PRIMARY KEY (MAHSBA, MADV, NGAY)
);

CREATE TABLE BENHNHAN (
	MABN VARCHAR2(10),
	MACSYT VARCHAR2(10),
	TENBN VARCHAR2(50),
	CMND VARCHAR2(32),
	NGAYSINH DATE,
	SONHA INT,
	TENDUONG VARCHAR2(50),
	QUANHUYEN VARCHAR2(50),
	TINHTP VARCHAR2(50),
	TIENSUBENH VARCHAR2(255),
	TIENSUBENHGD VARCHAR2(255),
	DIUNGTHUOC VARCHAR2(255),
	CONSTRAINT PK_BENHNHAN PRIMARY KEY (MABN)
);

CREATE TABLE CSYT(
	MACSYT VARCHAR2(10),
	TENCSYT VARCHAR2(50),
	DCCSYT VARCHAR2(255),
	SDTCSYT CHAR(10),
	CONSTRAINT PK_CSYT PRIMARY KEY (MACSYT)
);

CREATE TABLE NHANVIEN(
	MANV VARCHAR2(10),
	HOTEN VARCHAR2(50),
	PHAI VARCHAR2(3) CHECK (PHAI IN(N'Nam',N'Nu')),
	NGAYSINH DATE,
	CMND VARCHAR2(32),
	QUEQUAN VARCHAR2(50),
	SODT CHAR(10),
	CSYT VARCHAR2(10),
	VAITRO VARCHAR2(20) CHECK (VAITRO IN (N'Thanh tra', N'Co so y te', N'Y si / Bac si', N'Nghien cuu')),
	CHUYENKHOA VARCHAR2(10),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY (MANV)
);

ALTER TABLE HSBA ADD CONSTRAINT FK_HSBA_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);
ALTER TABLE HSBA ADD CONSTRAINT FK_HSBA_NHANVIEN  FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV);
ALTER TABLE HSBA ADD CONSTRAINT FK_HSBA_CSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);
ALTER TABLE HSBA_DV ADD CONSTRAINT FK_HSBA_DV_HSBA FOREIGN KEY(MAHSBA)REFERENCES HSBA(MAHSBA);
ALTER TABLE BENHNHAN ADD CONSTRAINT FK_BENHNHAN_CSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CSYT FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT);