--Thanh tra chi co the doc tren cac quan he
GRANT SELECT ON QLCSYT.HSBA TO R_THANHTRA;
GRANT SELECT ON QLCSYT.HSBA_DV TO R_THANHTRA;
GRANT SELECT ON QLCSYT.BENHNHAN TO R_THANHTRA;
GRANT SELECT ON QLCSYT.CSYT TO R_THANHTRA;
GRANT SELECT ON QLCSYT.NHANVIEN TO R_THANHTRA;