--Thanh tra chi co the doc tren cac quan he
GRANT SELECT ON HSBA TO R_THANHTRA;
GRANT SELECT ON HSBA_DV TO R_THANHTRA;
GRANT SELECT ON BENHNHAN TO R_THANHTRA;
GRANT SELECT ON CSYT TO R_THANHTRA;
GRANT SELECT ON NHANVIEN TO R_THANHTRA;