GRANT SELECT ON QLCSYT.HSBA TO R_NGHIENCUU;
GRANT SELECT ON QLCSYT.HSBA_DV TO R_NGHIENCUU;
GRANT SELECT, UPDATE ON QLCSYT.NHANVIEN TO R_NGHIENCUU;


-----------------  Tạo view hsba
CREATE OR REPLACE VIEW NGHIENCUU_HSBA AS
SELECT HS.* 
FROM NHANVIEN NV, HSBA HS
WHERE NV.CSYT = HS.MACSYT AND NV.CHUYENKHOA = HS.MAKHOA;

GRANT SELECT ON QLCSYT.NGHIENCUU_HSBA TO R_NGHIENCUU;


-----------------  Tạo view hsba_dv

CREATE OR REPLACE VIEW NGHIENCUU_HSBA_DV AS
SELECT HSDV.*
FROM HSBA_DV HSDV, HSBA HS, NHANVIEN NV
WHERE HSDV.MAHSBA = HS.MAHSBA AND NV.CSYT = HS.MACSYT AND NV.CHUYENKHOA = HS.MAKHOA;

GRANT SELECT ON QLCSYT.NGHIENCUU_HSBA_DV TO R_NGHIENCUU;