--SYS
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--Tao user giam doc so
CREATE USER GDS IDENTIFIED BY GDS;
GRANT CREATE SESSION TO GDS;
GRANT SELECT ON QLCSYT.NHANVIEN TO GDS;

--Tao cac user giam doc csyt
CREATE USER GDCSYT1 IDENTIFIED BY GDCSYT1;
GRANT CREATE SESSION TO GDCSYT1;
GRANT SELECT ON QLCSYT.NHANVIEN TO GDCSYT1;

CREATE USER GDCSYT2 IDENTIFIED BY GDCSYT2;
GRANT CREATE SESSION TO GDCSYT2;
GRANT SELECT ON QLCSYT.NHANVIEN TO GDCSYT2;

CREATE USER GDCSYT3 IDENTIFIED BY GDCSYT3;
GRANT CREATE SESSION TO GDCSYT3;
GRANT SELECT ON QLCSYT.NHANVIEN TO GDCSYT3;

--Tao user y bac si
CREATE USER YBACSI IDENTIFIED BY YBACSI;
GRANT CREATE SESSION TO YBACSI;
GRANT SELECT ON QLCSYT.NHANVIEN TO YBACSI;

--Grant quyen cho LBACSYS truy cap vao bang NHANVIEN de thuc hien OLS
GRANT ALL PRIVILEGES ON QLCSYT.NHANVIEN TO LBACSYS;

--Unlock user LBACSYS
ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK;
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;


--Chay voi vai tro LBACSYS
--Grant quyen cho QLCSYT cac packages
--Grant quyen tao components de tao label, compartment va y bac si
GRANT EXECUTE ON SA_COMPONENTS TO QLCSYT;
--Grant quyen gan label cho user
GRANT EXECUTE ON SA_USER_ADMIN TO QLCSYT WITH GRANT OPTION;
--Grant quyen tao label
GRANT EXECUTE ON SA_LABEL_ADMIN TO QLCSYT WITH GRANT OPTION;
--Grant quyen gan policy cho table/schema
GRANT EXECUTE ON SA_POLICY_ADMIN TO QLCSYT WITH GRANT OPTION;
--Grant quyen chuyen chuoi thanh so label
GRANT EXECUTE ON CHAR_TO_LABEL TO QLCSYT WITH GRANT OPTION;


--GRANT LBAC_DBA TO QLYCSYT;
--GRANT EXECUTE ON sa_audit_admin  TO QLYCSYT;


--Grant quyen thuc thi cac ham sa_sysdba de tao policy
GRANT EXECUTE ON SA_SYSDBA TO QLCSYT;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO QLCSYT;
GRANT LBAC_DBA TO QLCSYT;

--SYS
ALTER SESSION SET container = cdb$root;

--Tao policy (policy + nhan du lieu va nhan nguoi dung)
BEGIN
	SA_SYSDBA.CREATE_POLICY(
		policy_name => 'THONGBAO_CSYT',
		column_name => 'OLS_COLUMN'
	);	
END;  --Tao ra role THONGBAO_CSYT_DBA

--Grant quyen de quan ly va duy tri hoat dong cua chinh sach
GRANT THONGBAO_CSYT_DBA TO QLCSYT;

--Tao level (theo muc do gdso -> gdcsyt -> ybsi)
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_CSYT', 100, 'GDS', 'Giam Doc So');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_CSYT', 70, 'GDCSYT', 'Giam Doc CSYT');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('THONGBAO_CSYT', 40, 'YBS', 'Y Bac Si');

--Tao compartment (Chuyen sau -> noi tru -> ngoai tru)
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_CSYT', '200', 'DTCS', 'Dieu tri chuyen sau');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_CSYT', '300', 'DTNT', 'Dieu tri noi tru');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_CSYT', '400', 'DTNgT', 'Dieu tri ngoai tru');

--Tao group (Trung tam -> Can trung tam -> Ngoai thanh)
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_CSYT', '1', 'TT', 'Trung tam');
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_CSYT', '2', 'CTT', 'Can trung tam');
EXECUTE SA_COMPONENTS.CREATE_GROUP('THONGBAO_CSYT', '3', 'NT', 'Ngoai thanh');

--Set policy sau khi tao cho SYS
EXECUTE SA_USER_ADMIN.SET_USER.PRIVS('THONGBAO_CSYT', 'SYS', 'FULL');

--Tao bang thong bao
CREATE TABLE THONGBAO(
	NOIDUNG NVARCHAR2(1000),
	NGAYGIO DATE,
	DIADIEM NVARCHAR2(255)
);


--Tao LABEL
--Label giam doc so
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'THONGBAO_CSYT', label_tag => 1, label_value => 'GDS');


--Label giam doc csyt
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'THONGBAO_CSYT', label_tag => 210, label_value => 'GDCSYT:DTCS:CTT');


EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'THONGBAO_CSYT', label_tag => 220, label_value => 'GDCSYT:DTNT:NT');


EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'THONGBAO_CSYT', label_tag => 230, label_value => 'GDCSYT:DTNgT:TT');


--Label cho y bac si
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'THONGBAO_CSYT', label_tag => 110, label_value => 'YBS:DTNT:NT');


--Grant policy vao bang
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('THONGBAO_CSYT','QLCSYT','THONGBAO');
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name => 'THONGBAO_CSYT',
    schema_name => 'QLCSYT',
    table_name  => 'THONGBAO',
    table_options => 'READ_CONTROL, WRITE_CONTROL');
END;

--Gan nhan cho row
update qlcsyt.thongbao set ols_column = char_to_label('THONGBAO_CSYT', 'GDS');

--Grant label cho user
BEGIN
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_CSYT', 'GDS', 'GDS:DTNT,DTNgT,DTCS:TT,CTT,NT'); 
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_CSYT', 'GDCSYT01', 'GDCSYT:DTNT:NT'); --Dung
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_CSYT', 'GDCSYT02', 'GDCSYT:DTCS:CTT'); --Dung
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_CSYT', 'GDCSYT03', 'GDCSYT:DTNgT:NT'); --Sai
  SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_CSYT', 'YBACSI', 'YBS:DTNT:NT'); --Dung
END;

GRANT SELECT, INSERT, UPDATE ON THONGBAO TO GDSO;
GRANT SELECT ON THONGBAO TO GDCSYT01;
GRANT SELECT ON THONGBAO TO GDCSYT02;
GRANT SELECT ON THONGBAO TO GDCSYT03;
GRANT SELECT ON THONGBAO TO YBS;

GRANT EXECUTE ON CHAR_TO_LABEL TO GDSO;
GRANT EXECUTE ON CHAR_TO_LABEL TO GDCSYT;
GRANT EXECUTE ON CHAR_TO_LABEL TO GDCSYT2;
GRANT EXECUTE ON CHAR_TO_LABEL TO GDCSYT3;
GRANT EXECUTE ON CHAR_TO_LABEL TO YBS;

INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 1', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 1', 'GD CSYT Noi Tru - Ngoai Thanh');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 2', TO_TIMESTAMP('2022-02-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 2', 'GD CSYT Noi Tru - Ngoai Thanh');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 3', TO_TIMESTAMP('2022-03-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 3', 'GD CSYT Ngoai Tru - Trung Tam');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 4', TO_TIMESTAMP('2022-04-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 4', 'GD CSYT Ngoai Tru - Trung Tam');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 5', TO_TIMESTAMP('2022-05-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 5', 'YBS Ngoai Tru - Trung Tam');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 6', TO_TIMESTAMP('2022-06-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 6', 'YBS Noi Tru - Ngoai Thanh');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 7', TO_TIMESTAMP('2022-07-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 7', 'YBS Noi Tru - Ngoai Thanh');
INSERT INTO QLCSYT.THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, GUIDEN) VALUES ('NOI DUNG 9', TO_TIMESTAMP('2022-07-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 9', 'GD CSYT Chuyen Sau - Can Trung Tam');

select * from THONGBAO;

